### ISSUE TITLE
Is 10 times US summon being logged correctly?

### ISSUE THREAD

**Issue by Hastebro** [porksmash/swarfarm_io#21]
After doing a 10 times summoning of Unknown Scrolls for the event, I opened the "summons.cvs" file that is generated by swproxy and noticed it recorded only the first monster of the 10 times summon.

So I wondered if the plugin is recording that correctly.

**Comment by porksmash** [comment]
Yes, the plugin hands over all 10 summons and the server side code was updated on May 17th to process all of them with this commit: aa4719d573c7a7602730ab04757f8ab79ef1f2ce
