### ISSUE TITLE
Feature - Most used monsters

### ISSUE THREAD

**Issue by Hastebro** [porksmash/swarfarm_io#23]
Not sure if SWProxy is able to get the team composition data, but it would be interesting to know which monsters/teams are the most used in a given floor of a Dungeon and of ToA.

It would also be interesting for Arena and Guild Wars, but I can also see how that information could affect the meta after enough data is logged.

**Comment by porksmash** [comment]
We don't currently track monsters used. I believe the game data does include that, though. It would have to be limited to just the monster itself, not rune builds and any other data. I'll look into it some more. It will require an update to the plugin as well.

**Comment by Hastebro** [comment]
I realized that this feature might not be needed after all, at least not for dungeons. I completely forgot that the "Monster Used" data is in-game, which shows the top 15 monsters used in successful runs in the runes and elemental dungeons.

Could still be interesting to log monsters for HoH and ToA.

**Comment by porksmash** [comment]
I don't plan to keep track of monsters used. The game data from a run result does have the monsters used in the team, but it isn't given as 'Baretta, Belladeon, Veromos'. What it has is 103919231, 8481731712, 27172371, etc. Those numbers are unique IDs assigned to your specific Baretta, Belladeon, and Veromos, but there is no actual indication that 103919231 == Baretta
