### ISSUE TITLE
Log world boss drops

### ISSUE THREAD

**Issue by porksmash** [porksmash/swarfarm_io#25]

**Comment by ikee** [comment]
Hi!

I am very interested in this feature, and I am currently looking into modifying the python parser my self to save more data from this. If you find it useful, how difficult would it be to add a world boss log? Would you accept other people to work on the page if it would help to push the feature faster? :) 

I am also kind of interested in mining the data to find co-relations between stats, attributes, monster type, and runes to damage contribution, would this somehow be possible to push into the site?

Keep up the great work with the site, I really love your work!

**Comment by porksmash** [comment]
I'm adding the world boss logging as we speak!

I was not planning on logging teams used, though. The API requests and responses doesn't give you anything other than a list of monster IDs, which on their own don't contain any useful information. There's a chance I have a match in a user's profile, but then I have to snapshot all 20 monsters and runes. This is simply too much data to log for every world boss fight.

**Comment by porksmash** [comment]
World boss report is now live: https://swarfarm.com/data/log/world-boss/

Please raise any further problems/suggestions for it in a new issue.
