### ISSUE TITLE
Log shop data

### ISSUE THREAD

**Issue by nabakin** [porksmash/swarfarm_io#27]
I think it would be amazing if we could see some data on shop refreshes that way we can know definitively how much better shop refreshes are than premium packs.

I can't express how awesome it is to have exact stats to base my decisions in Summoner's War.  Thanks for your amazing work :)

**Comment by porksmash** [comment]
That's a good one to add. I'll have to double check and make sure we can tell the difference between an actual refresh and just seeing the same list again. I think the timer will indicate that.

**Comment by porksmash** [comment]
Shop logging was just added. Will start collecting some data and working on the display.
