### ISSUE TITLE
Monsters used in dungeons data set

### ISSUE THREAD

**Issue by michael-luo** [porksmash/swarfarm_io#33]
Hi, I'm not sure if this is the right place to ask, but how would I be able to access data for each and every dungeon run recorded by players that publish data via the proxy?

I want to create a tool to predict what your success rate in GB10/DB10/etc. might be based on your team of monsters and their stats

**Comment by porksmash** [comment]
I don't collect the monsters used right now. There is a feature request on the sites feedback section but it's low priority.

**Comment by michael-luo** [comment]
wouldn't it be great to be able to predict team success rates? I'd be willing to implement that if I had the dataset

**Comment by porksmash** [comment]
It would be interesting, but definitely very difficult given the depth of monster customization that is possible. I don't foresee being able to store all the relevant data, either. To provide anything useful for analysis you need each monster's runes and stats too. That's a lot of data to store.

**Comment by michael-luo** [comment]
Yes, if it was a lot of data I would to use Spark or Hadoop to run jobs on the data sets. I'd be using machine learning to make predictions, and there are ways to get around the depth of monster customization!
